name: For King and Company
favicon: null
layout_spectrum: 0.39754
typography_spectrum: 0.40046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#013d71'
    - '#d0b2a4'
    - '#a48370'
    - '#2c79d1'
    - '#629de1'
  brandStrength: 0.4766870082821697
  lightness: 0.7128763240762055
  saturation: 0.75
  rhythmicContrast: 0.17842907016165555
purpose: []
